# server run with port 8080 - default
server:
  port: 8080

#config database connection with mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thymeleaf_ct3_week11?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true